version: '3.9'

services:
  api01: &api
    hostname: api01
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 140MB

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:80"

  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    
  db:
    image: postgres
    command: postgres -c config_file="/etc/database.conf"
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/script.sql"
      - "./database.conf:/etc/database.conf"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "220MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rinha" ]
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024-q1